version: "2"
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unparam
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
