name: Go

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Get dependencies
        run: |
          go mod download

      - uses: setare/go-lint-action@v0.1.2

  security:
    name: Security checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        env:
          GOPRIVATE: github.com/setare
        run: |
          go mod download

      - uses: setare/go-gosec-action@v0.2.2

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs:
      - lint
      - security
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Get dependencies
        run: |
          go mod download

      - name: Unit tests
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out
